services:
  devcontainer:
    container_name: devcontainer
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile

  node:
    image: node:16-alpine
    container_name: snear_api_node
    restart: always
    working_dir: /var/api
    command: sh -c "npm install && npm run dev"
    environment:
      PORT: 3000
      POSTGRES_USER: __USERNAME__
      POSTGRES_PASSWORD: __PASSWORD__
      POSTGRES_DB: __DATABASENAME__
    ports:
      - 8080:3000 
    volumes:
      - .:/var/api

  database:
    image: postgres:alpine
    container_name: snear_api_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: __USERNAME__
      POSTGRES_PASSWORD: __PASSWORD__
      POSTGRES_DB: __DATABASENAME__